[package]
name = "sandbox"
version = "0.1.0"
authors = ["yanbowen1994 <511838976@qq.com>"]
edition = "2018"

[dependencies]
dnet-types = { path = "../dnet-types" }
ipconfig = "0.2.1"
duct = "0.12"
err-derive = "0.1.5"
