Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"

    config.vm.box_check_update = false

    config.vm.network "private_network", ip: "192.168.50.10"

    config.vm.provider "virtualbox" do |vb|

        vb.gui = true

        vb.name = "vagrant_ubuntu16"

        vb.memory = "2048"

    end

    config.vm.provision :shell, path: "build.sh"

end