[package]
name = "ovrouter"
version = "0.1.0"
authors = ["yanbowen <bowen.yan@gitblit.com>"]

[dependencies]
chrono = "*"
os_type = "*"
regex = "*"
foundationdb = "0.2.0"
foundationdb-sys = "0.1.1"
curl = "*"
serde = "1.0.82"
serde_json = "1.0.33"
futures = "*"