[workspace]
members = [
    "dnet-cli",
    "dnet-gui",
    "dnet-daemon",
    "dnet-path",
    "dnet-types",
    "ipc-client",
    "router-plugin",
    "talpid-ipc",
    "tinc-plugin",
]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"
