[common]
home_path = "/opt/dnet"
log_level = "debug"
log_dir = "/var/log/dnet/"
mode = "proxy"
conductor_url = "https://huayi-api.vlan.cn"
accept_conductor_invalid_certs = true
username = "proxyovr"
password = "password"

[proxy]
local_ip = "192.168.1.1"
local_port = 10087
local_https_server_certificate_file = "/opt/dnet/cert.pem"
local_https_server_privkey_file = "/opt/dnet/key.pem"
public = true

[tinc]
port = 50069
external_boot = false