[package]
name = "ovrouter"
version = "0.1.0"
authors = ["yanbowen <bowen.yan@gitblit.com>"]

[[bin]]
name = "ovrouter"

[lib]
name = "ovrouter"

[dependencies]
log = "0.4.5"
fern = { version = "0.5", features = ["colored"] }

clap = "2.32.0"
config = "~0.9.1"
err-derive = "0.1.5"
duct = "0.12"

bytes = "0.4"

actix = "0.7"
actix-web = { version = "0.7", features=["ssl"] }

chrono = "0.4.6"
os_type = "2.2.0"
regex = "1.1.0"
reqwest = "0.9.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.33"
serde_derive = "1.0.85"
futures = "0.1.25"

uuid = "0.7.1"
openssl = "0.10"