[package]
name = "router-plugin"
version = "1.0.0"
authors = ["bowen.yan <bowen.yan@siteview.com>"]
edition = "2018"

[dependencies]
nix = "0.15"
serde = "1.0"
serde_derive = "1.0"
dnet-types = { path = "../dnet-types" }