Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"

    config.vm.box_check_update = false

    config.vm.network "private_network", ip: "192.168.50.11"

    config.vm.provider "virtualbox" do |vb|

        vb.gui = true

        vb.name = "vlan_dnetovr_compile"

        vb.memory = "2048"

        vb.cpus = 4

    end

    config.vm.synced_folder "./", "/mnt"

    config.vm.provision :shell, path: "build.sh"

end
