[package]
name = "setup"
version = "0.1.0"
authors = ["bowen.yan <bowen.yan@siteview.com>"]
edition = "2018"

[lib]

[dependencies]
config = "~0.9.1"
duct = "0.12"
os_type = "2.2.0"

serde = "1.0.82"
serde_json = "1.0.33"
serde_derive = "1.0.85"